"""empty message

Revision ID: a6838709d15f
Revises: fb07ff50f5b4
Create Date: 2017-02-26 14:51:30.376048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6838709d15f'
down_revision = 'fb07ff50f5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer', sa.Text(), nullable=True))
    op.add_column('townhalls', sa.Column('location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('townhalls', 'location')
    op.drop_column('questions', 'answer')
    # ### end Alembic commands ###
